---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homelab-secrets
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/JonSchaeffer/kubernetes-secrets
  ref:
    branch: main
  secretRef:
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homelab-secrets
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  force: false
  interval: 1m0s
  path: ./homelab
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-secrets