apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
  name: local-jonathanschaeffer-com-prod
  namespace: homeservices
spec:
  commonName: "*.local.jonathanschaeffer.com"
  dnsNames:
  - "local.jonathanschaeffer.com"
  - "*.local.jonathanschaeffer.com"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: local-jonathanschaeffer-com-production-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
  name: local-jonathanschaeffer-com-prod
  namespace: default
spec:
  commonName: "*.local.jonathanschaeffer.com"
  dnsNames:
  - "local.jonathanschaeffer.com"
  - "*.local.jonathanschaeffer.com"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: local-jonathanschaeffer-com-production-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
  name: local-jonathanschaeffer-com-prod
  namespace: traefik
spec:
  commonName: "*.local.jonathanschaeffer.com"
  dnsNames:
  - "local.jonathanschaeffer.com"
  - "*.local.jonathanschaeffer.com"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: local-jonathanschaeffer-com-production-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
  name: local-jonathanschaeffer-com-prod
  namespace: longhorn-
spec:
  commonName: "*.local.jonathanschaeffer.com"
  dnsNames:
  - "local.jonathanschaeffer.com"
  - "*.local.jonathanschaeffer.com"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: local-jonathanschaeffer-com-production-tls