apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitwarden
  template:
    metadata:
      labels:
        app: bitwarden
    spec:
      containers:
      - name: bitwarden
        image: vaultwarden/server:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: vw-data
          mountPath: /data
      volumes:
      - name: vw-data
        hostPath:
          path: /vw-data/
---
apiVersion: v1
kind: Service
metadata:
  name: bitwarden
spec:
  selector:
    app: bitwarden
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 80
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vw-data-pv
spec:
  capacity:
    storage: 10Gi  # Adjust the storage capacity as needed
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /vw-data/

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vw-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Adjust the storage capacity matching the PV
  selector:
    matchLabels:
      pv-name: vw-data-pv  # Label selector to match the PV
