apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: homeservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud
        image: lscr.io/linuxserver/nextcloud:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Etc/UTC"
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: data-volume
          mountPath: /data
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: nextcloud-config-pvc
      - name: data-volume
        persistentVolumeClaim:
          claimName: nextcloud-data-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: homeservices
spec:
  selector:
    app: nextcloud
  ports:
    - protocol: TCP
      port: 5656
      targetPort: 443
  type: ClusterIP

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-config-pvc
  namespace: homeservices
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Adjust the storage capacity as needed

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pvc
  namespace: homeservices
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi # Adjust the storage capacity as needed
