apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: homeservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - name: radarr
        image: lscr.io/linuxserver/radarr:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Etc/UTC"
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: movies-volume
          mountPath: /movies
        # - name: downloads-volume
        #   mountPath: /downloads
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: downloads
      - name: downloads-volume
        persistentVolumeClaim:
          claimName: radarr-downloads-pvc
      # - name: movies-volume
      #   hostPath:
      #     path: /mnt/nas/Media/Movies
      #     type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: homeservices
spec:
  selector:
    app: radarr
  ports:
    - protocol: TCP
      port: 7878
      targetPort: 7878
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  namespace: homeservices
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi # Adjust the storage capacity as needed

# ---
#
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: radarr-downloads-pvc
#   namespace: homeservices
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 50Gi # Adjust the storage capacity as needed
#   volumeName: downloads
