apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: homeservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - name: sonarr
        image: lscr.io/linuxserver/sonarr:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Etc/UTC"
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: tvshows-volume
          mountPath: /tv
        - name: downloads-volume
          mountPath: /downloads
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: sonarr-config-pvc
      - name: downloads-volume
        persistentVolumeClaim:
          claimName: downloads
      - name: tvshows-volume
        nfs:
          server: 192.168.0.215
          path: /mnt/md0/public/Media/TVShows

---

apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: homeservices
spec:
  selector:
    app: sonarr
  ports:
    - protocol: TCP
      port: 8989
      targetPort: 8989
  type: ClusterIP

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-pvc
  namespace: homeservices
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Adjust the storage capacity as needed
