apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: homeservices
spec:
  interval: 1m
  chart:
    spec:
      chart: truecharts/vaultwarden
      reconcileStrategy: Revision
      version: '24.0.6'
      sourceRef:
        kind: HelmRepository
        name: vaultwarden
        namespace: flux-system
      interval: 1m
